version: "3.8"  # Adjust if necessary

services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    build: ./webui
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
