import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { ProjectProvider } from "@/contexts/projectContext";

const font = Urbanist({subsets: ["latin"]}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ProjectProvider>
        <body className={font.className}>{children}</body>
      </ProjectProvider>
    </html>
  );
}
